### ISSUE TITLE
Finalize Initial Prototype

### ISSUE THREAD

**Issue by damithkothalawala** [damithkothalawala/pearson_nginx_admin#1]
We have to finalize initial UI Prototype

**Comment by damithkothalawala** [comment]
Hi Osala Please proceed with the initial UI Design

**Comment by damithkothalawala** [comment]
Use http://metroui.org.ua/templates/admin-sidebar-appbar.html  as a example

**Comment by OsalaV** [comment]
https://almsaeedstudio.com/   This is also a good admin panel

**Comment by damithkothalawala** [comment]
# Wow lets go with it then
